language: python

python: 
  - "2.7"
  
env:
  - FLASK=1.0

install:
  - pip install flask==$FLASK
  - pip install flask_sqlalchemy
  - pip install flask_marshmallow
  - pip install marshmallow-sqlalchemy

script:
  - python setup.py

